version: '3.9'

services:
  #  backend:
  #    platform: linux/amd64
  #    build: .
  #    ports:
  #      - "8080:8080"
  #    depends_on:
  #      - redis
  #    environment:
  #      - SPRING_DATA_REDIS_HOST=redis
  #      - SPRING_DATA_REDIS_PORT=6379
  redis:
    hostname: redis
    image: redis:latest
    ports:
      - "6379:6379"